### ISSUE TITLE
motionformer as baseline detailed training process?

### ISSUE THREAD

**Issue by daiguangzhao** [ekazakos/MTCN#1]
Thank you for your contribution! In reproducing your paper, the training code for motionformer as a baseline could not be found, the source code only has the transformer training model from 2017. If, I want to use motionformer as a baseline, how can I train and test it on EGTEA?

**Comment by JaesungHuh** [comment]
Hi daiguangzhao, 
We have not used the motionformer for train and test it on EGTEA. 
For the Motionformer for Epic-kitchens, we used pre-extracted features using the model that could be found in the [official github](https://github.com/facebookresearch/Motionformer). I guess you should fine-tune the motionformer using EGTEA and extract the features for that.

**Comment by daiguangzhao** [comment]
Yes, thank you for your reply. My method is using motionformer as the baseline and I want to train and test on EGTEA, do you have some suitable suggestions?

**Comment by JaesungHuh** [comment]
I'm sorry but we only used Motionformer for feature extraction and therefore we do not have suggestions for fine-tuning it. You could start with modifying epic-kitchens configuration file.
Thanks.

**Comment by daiguangzhao** [comment]
ok, thank you.
